### ISSUE TITLE
Error popup window: There was an error which prevented the batch from being processed.

### ISSUE THREAD

**Issue by pbakes** [iPzard/mkvtoolnix-batch-tool#14] opened 2021-01-23 20:49 UTC
Using 2.0.2. It's been working on other TV shows but not working for Cheers Season 3. Srt and Mkv files have matching filenames.

![Capture](https://user-images.githubusercontent.com/38716120/105613730-57c6bb80-5d79-11eb-8fb0-2646d5e7888b.PNG)

**Comment by iPzard** [comment] 2021-01-23 22:27
Thanks for reporting this! This particular error happens when there's a failure to communicate with the microservices. I'm guessing you (correctly) selected "allow" network communication when originally installing - otherwise, other shows wouldn't work either.. but that's one reason this error happens. 

Another reason this can happen is if one, or more, of the videos and/or subtitle files are not valid (e.g., from an incomplete download or something). I have a few troubleshooting steps I'm hoping you can try out, which should help us get to the bottom of this. 

1. Can you please check and ensure each file is valid; i.e., video plays, and subtitle opens in a text editor, such as notepad.
2. If the files turn out to be valid, there's probably a bug in the software that I need to fix.. If so, would you mind sending me a list of the file names, and any options you may have selected in the settings? I would be able to use that to debug something for a 2.0.3 release/patch. An easy way to get a list of file names is to open command prompt in the folder and type `dir > cheers.txt`, which creates a text file in that directory containing a list of all the file names. Alternatively, feel free to just take a screenshot if you'd like.  

I'll probably update that message in the near future to make the potential issue(s) more clear. I realize in your situation the message is a bit vague.

**Comment by gbabichev** [comment] 2021-01-28 06:42
I also ran into this issue, and fixed it by opening the SRT with a program called "Subtitle Edit" and changing the encoding from Simplified Chinese to UTF8-Without BOM. 

My subs were in English, but for some reason the encoding of the file was Simplified Chinese, which caused this error. 

Thanks for making this utility! Saved me some time writing a PS Script :)

**Comment by iPzard** [comment] 2021-01-28 16:44
Thanks @gbabichev, and glad to help! The information you provided should help me track down the root cause of this, the files are supposed to be forced into UTF8, but apparently, some files may pass the UTF8  check w/o actually being UTF8 (or at least the type of UTF8 needed).

**Comment by iPzard** [comment] 2021-01-29 17:01
I've been testing a wide variety of encoding options, but they all are converted and merged successfully without issues. Any chance either of you can provide a copy of an `.srt` file that gives you trouble?

![test-result](https://user-images.githubusercontent.com/8584126/106304724-91cc0d80-6210-11eb-9934-ab7af9fc00ce.png)

**Comment by gbabichev** [comment] 2021-01-29 23:20
Sure, here is the SRT. I can include one with the MKV as well.

https://drive.google.com/file/d/1XioYfDAqBeUqTxqVaJZ4yMmordIgTk43/view?usp=sharing

As soon as I use Subtitle Edit to change the encoding to UTF8, the batch
tools starts to work.

**Comment by iPzard** [comment] 2021-01-30 01:33
This is excellent, I appreciate you helping me track this down @gbabichev ! I've been able to reproduce and fix the issue with the file you've provided, version [2.0.3 has been released](https://github.com/iPzard/mkvtoolnix-batch-tool/releases), in which this issue is no longer present.

**Closed by iPzard** 2021-01-30 01:33 UTC
Labels: bug 🦟

**Comment by shekky** [comment] 2021-02-24 07:55
I am getting the same error, but I am not using text-based .srt subtitles. I'm using image-based .sup subtitles.

**Comment by iPzard** [comment] 2021-02-24 08:04
Mind sharing one of the subtitle files giving you issues? If so, I can take a look,.probably some time next week.

**Comment by shekky** [comment] 2021-02-24 08:24
Sure. Here are all the subs that were in the input folder.
[Season 4 Subs.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/6034429/Season.4.Subs.zip)

**Comment by iPzard** [comment] 2021-03-02 02:35
@shekky Thanks for your patience and providing those files! It looks like when trying to auto-determine the language it requires a string of text and was throwing an error when provided images instead for this. 

I've released a patch for this in ([v2.1.1](https://github.com/iPzard/mkvtoolnix-batch-tool/releases)) which should resolve your issue and get you all squared away. 

Though, if you continue to have issues, please feel free to comment here or open a new issue and I can dig into it deeper.

**Comment by iPzard** [comment] 2021-03-02 02:37
@shekky Thanks for your patience and providing those files! It looks like when trying to auto-determine the language it requires a string of text and was throwing an error when provided images instead for this. 

I've released a patch in [v2.1.1](https://github.com/iPzard/mkvtoolnix-batch-tool/releases/tag/v2.1.1) today which should resolve your issue and get you all squared away. But if you continue to have issues, please feel free to comment here or open a new issue and I can dig into it deeper.

**Comment by shekky** [comment] 2021-03-02 06:07
That did the trick. Thanks.

**Comment by iPzard** [comment] 2021-03-02 15:45
No problem, thanks for confirming!
