### ISSUE TITLE
Subtitle language not set.

### ISSUE THREAD

**Issue by Certefied** [iPzard/mkvtoolnix-batch-tool#49] opened 2021-12-10 22:47 UTC
Hi, i just discovered this fantastic tool. Just one thing i cant seem te get is the language in the subtitle file when it is merged.
In every file 01 appears and no language. 

My file name is like this
This Show S05E01 Dutch.srt
[This Show S05E01 Dutch.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/7695817/This.Show.S05E01.Dutch.zip)

Please tell me if I am doing something wrong.

Greets

**Comment by garylisk** [comment] 2021-12-27 04:12
I, too, have noticed this, but I bet it's not a bug. I wanted to post about it as a feature request, though. The tool allows you to set the Default Track to a specific language, but then adds the newly merged subs as "Undefined" so they would never be default. You can get them to be default, however, if you also tell the tool to remove all the other subs.

My suggestion is thus:
1. Allow setting of language to the subs that will be merged.
2. If multiple sub files are being merged, maybe allow filenames to contain language coding at the start or end of the filename, such as "en this show S05E01.ass" or even something like "This Show S05E01.en.ass" - I am not a clever man, maybe this is too much of an ask.
3. Allow replacement of specific subtitle tracks. For example, if the English subtitles in the .mkv are not satisfactory, and I found better ones, have an option  for "Replaced Language" and we could then select "English" - This would cause the tool to remove the existing "En" subs and insert the new subs, giving them the "En" language.

**Comment by reaseno** [comment] 2022-01-06 08:32
It would be nice to be able to add language information based on the subtitle name, otherwise it is confusing after merging.

Optimal would be to choose the default that filters like XySubFilter also use to detect the language for external subtitles:

Title.Language.ext

**Comment by iPzard** [comment] 2022-01-15 18:23
Hey everyone, thanks for all the input here! Just want to confirm this is a bug, currently the language is (supposed to be) [set automatically](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L152) while merging the subtitles, based on the language of the text in the file. 

I tested with the file provided and am experiencing this bug as well. I'll try to play around with the file provided to see where the issue is and what needs to be done so the language is automatically detected. There was another problem area that was pointed out as well..  

- Multiple subtitle files of default language.. it looks like [currently](https://github.com/iPzard/mkvtoolnix-batch-tool/blob/d8a45e6f1a5c6e3004eedfe04dcd445b920b7010/resources/modules/mkvtoolnix.py#L92) they will all be flagged as the default

I think an additional naming convention fallback like `.forced` or `.default` (either one) is a reasonable request to solve for this. I created [Issue 51](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/51) to manage and track that. Feel free to chime in there if anything else comes to mind or if I might have missed something. 

For this current issue that @Certefied has opened up, with the subtitle being marked as having an `undefined` language.. I'll look into that and update here as things progress. And thanks again everyone! Feedback like this has helped shape this tool to what it is today, so it's always very much appreciated!!

**Comment by iPzard** [comment] 2022-01-16 00:55
I've updated `TextBlob` to the latest version and added some regex substitutions to the evaluated subtitle text, in order to remove newline characters and lines that start with numbers _(e.g., 00:01:45,856 --> 00:01:49,678)_ which seemed to be confusing the underlining Google Translate API in tests performed. Seems to be working as expected now, at least with the subtitle files I tested on (including the one provided by @Certefied). 

Once [Issue 51](https://github.com/iPzard/mkvtoolnix-batch-tool/issues/51) is complete there will be additional user recourse if similar issues arise, since they'll be able to force the language and/or default track as needed. 

I've created a new release which you can find here, feel free to update this thread if any issues are noticed:
https://github.com/iPzard/mkvtoolnix-batch-tool/releases

**Comment by Certefied** [comment] 2022-01-16 12:03
Hi,

Thnx for fixing this. The language is now set corect. Love your tool, sutch
a time saver.

Greets

Certefied.

Op zo 16 jan. 2022 01:55 schreef Daniel W. ***@***.***>:

**Comment by iPzard** [comment] 2022-01-16 17:54
Sweeet, and no problem!! Thanks for confirming!

**Comment by BitNin** [comment] 2022-01-19 02:47
Works brilliantly.  I just threw it against a movie that has 11 associated srt's.  It correctly identified all but 3:  Korean, Ukrainian, and Russian.

[Subs.zip](https://github.com/iPzard/mkvtoolnix-batch-tool/files/7893685/Subs.zip)

I've attached a zip with the three srt's that it couldn't identify.  I haven't done any further testing but I will continue to find other media with subs for these languages and see if it'll pick those up.

Thanks again for all your work!

**Comment by iPzard** [comment] 2022-01-21 04:51
Appreciate the test files! Was able make a few updates to remove language detection inconsistencies. Looks like it's successfully detecting all languages provided correctly with the test files provided. This patch as been added to the newest release:
[MKVToolNix Batch Tool releases](https://github.com/iPzard/mkvtoolnix-batch-tool/releases)

Will close this ticket now, but let me know if you're still having issues after updating. Thanks again!!

**Closed by iPzard** 2022-01-21 04:51 UTC
Labels: bug 🦟, preserved 💾
